containerImages:
  studio:
    frontend:
      version: 1.0.0
    backend:
      version: master
organisations:
  orga1:
    name: Orga1
  orga2:
    name: Orga2
channels:
  channel1:
    type: 2-orgs-policy-any
    organisations:
      orga1: chanOrga1
      orga2: chanOrga2